subscription MessageSended($sender:Int!,$receiver:Int!){
    messageSended(sender:$sender,receiver:$receiver) {
        id
        title
        sendTime
        receiverStudentId
        senderStudentId
    }
}