query getStudentPosts($data: GetStudentInput!, $offset: Int, $limit: Int) {
  student(data: $data) {
    posts(offset: $offset, limit: $limit) {
      color
      updatedAt
      createdAt
      id
      text
    }
  }
}
