query getSendedMessagesTo($data: GetStudentInput!, $receiverId: Int!) {
  student(data: $data) {
    sendedMessagesTo(toId: $receiverId) {
      id
      title
      sendTime
      receiverStudentId
      senderStudentId
    }
  }
}
