version: '3.8'
services:
  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api 
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

  postgres:
    image: postgres:latest
    container_name: students_db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    env_file:
      - .env
    volumes:
      - redis:/var/lib/redis/data
volumes:
  postgres:
    name: postgres-data
  redis:
    name: redis-data