version: '3.8'
services:
  postgres:
    container_name: students_db
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - 5432:5432
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis:/var/lib/redis/data
volumes:
  data:
  redis: